version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
  migrate:
    aliases:
      - gen
    desc: "run migration"
    cmd: go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
